# Generated by Django 5.1 on 2025-06-07 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NutriScan_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredientanalysis',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AddField(
            model_name='ingredientanalysis',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='analysis_images/'),
        ),
    ]
